[project]
name = "dova"
version = "0.1.0"
description = "DOVA is a local first agentic voice assistant designed to co-exist with your system."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepagents>=0.6.11",
    "langchain-ollama>=1.1.0",
    "langsmith[sandbox]>=0.9.1",
    "pyautogui>=0.9.54",
    "pyperclip>=1.11.0",
    "pyttsx3>=2.99",
    "rich>=15.0.0",
    "sounddevice>=0.5.5",
    "speechrecognition[audio,vosk]>=3.17.0",
]

[dependency-groups]
dev = [
    "commitizen>=4.16.4",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
